-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Jul 18, 2022 at 06:44 PM
-- Server version: 10.4.21-MariaDB
-- PHP Version: 8.0.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `u977028740_corivalCRM`
--

-- --------------------------------------------------------

--
-- Table structure for table `hotel`
--

CREATE TABLE `hotel` (
  `data_id` int(10) NOT NULL,
  `hrms` varchar(100) DEFAULT NULL,
  `ats` varchar(50) DEFAULT NULL,
  `crm` varchar(100) DEFAULT NULL,
  `erp` varchar(100) DEFAULT NULL,
  `pos` varchar(100) DEFAULT NULL,
  `rms` varchar(100) DEFAULT NULL,
  `cm` varchar(123) DEFAULT NULL,
  `pms` varchar(100) DEFAULT NULL,
  `ibe` varchar(100) DEFAULT NULL,
  `crs` varchar(50) NOT NULL,
  `hotel_name` varchar(200) DEFAULT NULL,
  `website` varchar(200) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `street` varchar(196) DEFAULT NULL,
  `city` varchar(111) DEFAULT NULL,
  `state` varchar(123) DEFAULT NULL,
  `zipcode` varchar(100) DEFAULT NULL,
  `prefix` varchar(6) DEFAULT NULL,
  `first_name` varchar(110) DEFAULT NULL,
  `last_name` varchar(100) DEFAULT NULL,
  `title` varchar(44) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `contact_number` varchar(123) DEFAULT NULL,
  `number_of_rooms` int(15) DEFAULT NULL,
  `hotel_class` int(11) DEFAULT NULL,
  `adr` varchar(50) DEFAULT NULL,
  `services` varchar(250) DEFAULT NULL,
  `type_of_hotel` varchar(127) DEFAULT NULL,
  `ownership` varchar(100) DEFAULT NULL,
  `chain_name` varchar(100) DEFAULT NULL,
  `facebook_url` varchar(200) DEFAULT NULL,
  `alexa_rank` varchar(50) DEFAULT NULL,
  `monthly_visitor` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `hotel`
--

INSERT INTO `hotel` (`data_id`, `hrms`, `ats`, `crm`, `erp`, `pos`, `rms`, `cm`, `pms`, `ibe`, `crs`, `hotel_name`, `website`, `country`, `street`, `city`, `state`, `zipcode`, `prefix`, `first_name`, `last_name`, `title`, `email`, `contact_number`, `number_of_rooms`, `hotel_class`, `adr`, `services`, `type_of_hotel`, `ownership`, `chain_name`, `facebook_url`, `alexa_rank`, `monthly_visitor`) VALUES
(1, '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '17', '13', '14', '15', '16', '18', '19', '20', '21', '22', '23', 24, 25, '26', '27', '28', '29', '30', '31', '32', '33'),
(3, '', 'Guestline PMS', '', '', 'Micros', 'One Yield', '', 'Opera PMS', '', 'MARSHA', 'Ambassadors Bloomsbury', 'ambassadors.co.uk', 'United Kingdom', '12 Upper Woburn Pl, Bloomsbury', 'London', '', 'WC1H 0HX', '', 'Johny', 'Jones', 'General Manager', 'generalmanager@ambassadors.co.uk', '44 20 7693 5400', 100, 4, 'US$ 97 - US$ 215', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(4, 'Opera PMS', 'Opera PMS', '', '', 'Micros', 'One Yield', '', 'Opera PMS', '', 'MARSHA', 'The Ampersand Hotel', 'ampersandhotel.com', 'United Kingdom', '10 Harrington Rd, Kensington', 'London', '', 'SW7 3ER', '', 'Roberto', 'Pajares', 'General Manager', 'rp@ampersandhotel.com', '44 20 7589 5895', 111, 5, 'US$ 120 - US$ 174', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(5, 'Opera PMS', 'Opera PMS', '', '', '', '', '', 'Guestline PMS', '', 'Reseze', 'Antoinette Hotel', 'antoinettehotel.com', 'United Kingdom', 'The Broadway', 'London', '', 'SW19 1SD', '', 'Francesco', 'Bartolomei', 'General Manager', 'francescob@antoinettehotels.com', '442000000000', 100, 3, 'US$ 105 - US$ 344', 'Meeting Rooms', 'Indepedent hotel', '', '', '', '', ''),
(6, 'Opera PMS', 'Opera PMS', '', '', '', '', '', 'Opera PMS', '', 'Booking.com', 'The Athenaeum Hotel', 'athenaeumhotel.com', 'United Kingdom', '116 Piccadilly, Mayfair', 'London', '', 'W1J 7BJ', '', 'Jeremy', 'Hopkins', 'General Manager', 'hopkinsj@athenaeumhotel.com', '44 20-7499-3464', 164, 5, 'Not Available', 'None', 'Independent hotel', '', '', '', '', ''),
(7, '', 'Opera PMS', '', '', 'Micros', 'Infor EzLITE revenue management system', '', 'Opera PMS', '', 'Synxis', 'Baglioni Hotel London', 'baglionihotels.com', 'United Kingdom', '60 Hyde Park Gate, Kensington', 'London', '', 'SW7 5BB', '', 'Alessandro', 'Convertino', 'General Manager', 'a.convertino@baglionihotels.com', '44 20-7368-5700', 67, 5, 'US$ 75 - US$ 155', 'Meeting Room', 'Small Chain', '', '', '', '', ''),
(8, 'Opera PMS', '', '', '', 'Micros', 'Infor EzLITE revenue management system', '', 'Opera PMS', '', 'Synxis', 'Bayswater Inn Hotel', 'bayswaterinnhotel.com', 'United Kingdom', '16 Prince\'s Square', 'London', '', 'W2 4NT', '', 'David', 'Gesto', 'Cluster General Manager', 'david.gesto@bayswaterinnhotel.com', '44 20 7727 8621', 140, 3, 'US$ 86 - US$ 109', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(9, 'Opera PMS', '', '', '', 'Micros', 'Infor EzLITE revenue management system', '', 'Opera PMS', '', 'Synxis', 'Hotel Berjaya Eden Park London', 'berjayahotel.com', 'United Kingdom', '35-39 Inverness Terrace', 'London', '', 'W2 3JS', '', 'Kathleen', 'Tay', 'General Manager', 'gm.london@berjayahotel.com', '44 20 7221 2220', 114, 3, 'US$ 63 - US$ 98', 'Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(10, 'Opera PMS', '', '', '', '', '', '', 'Opera PMS', '', 'Trust International', 'Blakemore Hyde Park Hotel', 'blakemorehydepark.com', 'United Kingdom', '30 Leinster Gardens', 'London', '', 'W2 3AN', '', 'Pradeep', 'Gurtata', 'General Manager', 'pradeep.gurtata@starcrown.com', '442000000000', 164, 4, 'US$ 136 - US$ 390', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(11, '', '', '', '', '', '', '', 'Guestline PMS', '', 'Checkfront', 'The Bromley Court Hotel', 'bromleycourthotel.co.uk', 'United Kingdom', 'Bromley Hill, Bromley', 'London', '', 'BR1 4JD', '', 'Graham', 'Rothwell', 'General Manager', 'g.rothwell@bromleycourthotel.co.uk', '442000000000', 117, 3, 'US$ 120 - US$ 169', 'Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(12, 'Opera PMS', 'Opera PMS', '', '', '', '', '', 'Opera PMS', '', 'Navis Technology', 'Central Park Hotel', 'centralparklondon.co.uk', 'United Kingdom', '49-67 Queensborough Terrace', 'London', '', 'W2 3SY', '', 'Angelika', 'Meltzer', 'General Manager', 'angelika.meltzer@centralparklondon.co.uk', '442000000000', 295, 3, 'US$ 172 - US$ 369', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(13, 'Opera PMS', 'Opera PMS', '', '', 'Micros', 'One Yield', '', 'Opera PMS', '', 'MARSHA', 'The Clarendon Hotel', 'clarendonhotel.com', 'United Kingdom', '8-16 Montpelier Row, Blackheath', 'London', '', 'SE3 0RW', '', 'Ken', 'Milton', 'General Manager', 'ken@clarendonhotel.com', '44 208 318 4321', 180, 3, 'US$ 150 - US$ 591', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(14, 'Opera PMS', 'Opera PMS', '', '', '', '', '', 'Opera PMS', '', 'Bookonthenet', 'Claridge`S Hotel', 'claridges.co.uk', 'United Kingdom', 'Brook St, Mayfair', 'London', '', 'W1K 4HR', '', 'Paul', 'Jackson', 'General Manager', 'pjackson@claridges.co.uk', '442000000000', 190, 5, 'US$ 93 - US$ 120', 'Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(15, '', '', '', '', 'Micros', 'IDeas', 'Choiceadvantage', 'Brilliant PMS (Amadeus)', '', 'Amadeus', 'Goodenough Club', 'club.goodenough.ac.uk', 'United Kingdom', '23 Mecklenburgh Square', 'London', '', 'WC1N 2AD', '', 'Louise', 'O\'Gorman', 'General Manager', 'louise.o\'gorman@goodenough.ac.uk', '44 20 7837 8831', 63, 4, 'US$ 91 - US$ 124', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(16, '', 'Opera PMS', '', '', 'Micros', 'IDeas', 'Choiceadvantage', 'Opera PMS', '', 'Amadeus', 'Corinthia Hotel London', 'corinthia.com', 'United Kingdom', 'Whitehall Pl, Westminster', 'London', '', 'SW1A 2BD', '', 'Matthew', 'Dixon', 'General Manager', 'matthew.dixon@corinthia.com', '44 20-7930-8181', 294, 5, 'US$ 83 - US$ 141', 'Meeting Rooms', 'Chain Hotel', '', '', '', '', ''),
(17, '', 'Opera PMS', '', '', 'Micros', 'IDeas', 'Choiceadvantage', 'Opera PMS', '', 'Amadeus', 'The Courthouse Hotel', 'courthouse-hotel.com', 'United Kingdom', '19 - 21 Great Marlborough St, Soho', 'London', '', 'W1F 7HL', '', 'Roy', 'Sommer', 'General Manager', 'roy.sommer@courthouse-hotel.com', '442000000000', 112, 5, 'US$ 93 - US$ 240', 'Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(18, '', 'Opera PMS', '', '', 'Micros', 'IDeas', 'Curtis - C', 'Opera PMS', '', 'Amadeus', 'Dolphin House Serviced Apartments', 'dolphinsquare.co.uk', 'United Kingdom', 'Dolphin Square, Chichester St, Pimlico', 'London', '', 'SW1V 3LX', '', 'Neil', 'Miller-Chalk', 'General Manager', 'nmchalk@dolphinsquare.co.uk', '44 20 7798 8000', 165, 4, 'US$ 97 - US$ 199', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(19, '', '', '', '', 'Micros', 'IDeas', 'Curtis - C', 'Opera PMS', '', 'Amadeus', 'Durrants Hotel', 'durrantshotel.co.uk', 'United Kingdom', '32 George St, Marylebone', 'London', '', 'W1H 5BJ', '', 'Ian', 'McIntosh', 'General Manager', 'ian.mcintosh@durrantshotel.co.uk', '44 20 7935 8131', 92, 4, 'US$ 99 - US$ 129', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(20, '', 'Opera PMS', '', '', 'Micros', 'One Yield', 'Curtis - C', 'Mews', '', 'MARSHA', 'Hotel Euston Square', 'euston-square-hotel.com', 'United Kingdom', '152-156 North Gower Street', 'London', '', 'NW1 2LU', '', 'Navin', 'Silwal', 'General Manager', 'navin.sillwal@euston-square-hotel.com', '44 20 7388 0099', 75, 3, 'US$ 239 - US$ 748', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(21, '', 'Opera PMS', '', '', '', '', 'Curtis - C', 'Opera PMS', '', 'Windsurfer CRS', 'Flemings Mayfair Hotel', 'flemings.co.uk', 'United Kingdom', '7-12 Half Moon St, Mayfair', 'London', '', 'W1J 7BH', '', 'Henrik', 'Muehle', 'General Manager', 'henrik.muehle@flemings.co.uk', '44 20-7499-0000', 129, 4, 'US$ 66 - US$ 122', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(22, '', 'Opera PMS', '', '', 'Micros', 'Ideas', 'Curtis - C', 'Mews', '', 'Choiceadvantage', 'Grand Plaza Serviced Apartment Hotel', 'grand-plaza.co.uk', 'United Kingdom', '42 Prince\'s Square', 'London', '', 'W2 4AD', '', 'Mohd', 'Jeffri', 'Chief Executive Officer', 'mohd.jeffri@grandplazaemail.co.uk', '44 20-7985-8000', 198, 4, 'US$ 85 - US$ 166', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(23, 'Opera PMS', '', '', '', 'Micros', 'Ideas', '', 'Mews', '', 'Choiceadvantage', 'The Park City Grand Plaza Kensington Hotel', 'parkcitylondon.com', 'United Kingdom', '18-30 Lexham Gardens, Kensington', 'London', '', 'W8 5JE', '', 'Alessandro', 'D\'Ambrosio', 'Front Desk Manager', 'alessandro@parkcitylondon.co.uk', '44 20 7341 7090', 62, 4, 'US$ 90 - US$ 144', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(24, 'Opera PMS', '', '', '', 'Micros', 'Ideas', '', 'Opera PMS', '', 'Choiceadvantage', 'Park International Hotel', 'parkinternationalhotel.com', 'United Kingdom', '117-129 Cromwell Rd, Kensington', 'London', '', 'SW7 4DS', '', 'Aflal', 'Jabir', 'Operations Manager', 'aflal.jabir@parkinternationalhotel.com', '44 20 7370 5711', 171, 4, 'US$ 91 - US$ 138', 'Meeting Room', 'Small Chain', '', '', '', '', ''),
(25, 'Opera PMS', '', '', '', 'Micros', 'Ideas', '', 'Opera PMS', '', 'Choiceadvantage', 'Royal Garden Hotel', 'royalgardenhotel.co.uk', 'United Kingdom', '2-24 Kensington High St, Kensington', 'London', '', 'W8 4PT', '', 'Mark', 'Anderson', 'Director of Sales and Marketing', 'markanderson@royalgardenhotel.co.uk', '44 20-7937-8000', 394, 5, 'US$ 83 - US$ 134', 'Meeting Rooms', 'Independent hotel', '', '', '', '', ''),
(26, '', 'Opera PMS', '', '', 'Micros', 'Ideas', '', 'Visual One', '', 'Choiceadvantage', 'Royal Garden Hotel', 'royalgardenhotel.co.uk', 'United Kingdom', '2-24 Kensington High St ,Kensington', 'London', '', 'W8 4PT', '', 'Sian', 'Walker', 'Marketing Manager', 'SianWalker@royalgardenhotel.co.uk', '44 0 20 7937 8000', 394, 5, 'US$ 78 - US$ 120', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(27, 'Opera PMS', 'Opera PMS', '', '', 'Micros', 'Ideas', '', 'Visual One', '', 'Choiceadvantage', 'Royal Garden Hotel', 'royalgardenhotel.co.uk', 'United Kingdom', '2-24 Kensington High St ,Kensington', 'London', '', 'W8 4PT', '', 'Oliver', 'Bateman', 'General Manager', 'OliverBateman@royalgardenhotel.co.uk', '44 0 20 7937 8000', 394, 5, 'US$ 81 - US$ 173', 'NONE', 'Independent hotel', '', '', '', '', ''),
(28, 'Opera PMS', 'Opera PMS', '', '', 'Micros', 'Ideas', '', 'Skytouch Technology', '', 'Choiceadvantage', 'Royal Garden Hotel', 'royalgardenhotel.co.uk', 'United Kingdom', '2-24 Kensington High St, Kensington', 'London', '', 'W8 4PT', '', 'Tim', 'Fryer', 'Deputy General Manager - Operations', 'timfryer@royalgardenhotel.co.uk', '44 20-7937-8000', 394, 5, 'US$ 101 - US$ 179', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(29, 'Opera PMS', '', '', '', 'Micros', 'Ideas', '', 'Skytouch Technology', '', 'Choiceadvantage', 'Royal Garden Hotel', 'royalgardenhotel.co.uk', 'United Kingdom', '24 Kensington High Street', 'London', '', 'W8 5', '', 'Oliver', 'Bateman', 'General Manager', 'obateman@royalgardenhotel.co.uk', '44 0 20 7937 8000', 394, 5, 'US$ 88 - US$ 147', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(30, '', 'Opera PMS', '', '', 'Micros', 'Ideas', '', 'Skytouch Technology', '', 'Choiceadvantage', 'Royal Garden Hotel', 'royalgardenhotel.co.uk', 'United Kingdom', '24 Kensington High Street', 'London', '', 'W8 5', '', 'Sian', 'Walker', 'Marketing Manager', 'swalker@royalgardenhotel.co.uk', '44 0 20 7937 8000', 394, 5, 'US$ 122 - US$ 400', 'Meeting Rooms', 'Independent hotel', '', '', '', '', ''),
(31, 'Opera PMS', 'Opera PMS', '', '', 'Micros', 'Ideas', '', 'Skytouch Technology', '', 'Choiceadvantage', 'Royal Lancaster London', 'royallancaster.com', 'United Kingdom', 'Lancaster Terrace', 'London', '', 'W2 2TY', '', 'Sally', 'Beck', 'General Manager', 'seb@lancasterlondon.com', '44 20 7551 6000', 416, 4, 'US$ 110 - US$ 318', 'Meeting Rooms', 'Independent hotel', '', '', '', '', ''),
(32, 'Opera PMS', 'Opera PMS', '', '', 'Micros', 'Ideas', '', 'Skytouch Technology', '', 'Choiceadvantage', 'Sarova Hotels Ltd', 'sarova.com', 'United Kingdom', '11 Thurloe Cl, Kensington', 'London', '', 'SW7 2RS', '', 'Karl', 'Wilson', 'General Manager', 'kwilson@sarova.com', '44 20 7589 5151', 194, 4, 'US$ 74 - US$ 140', 'Meeting Room', 'Chain Hotel', '', '', '', '', ''),
(33, 'Opera PMS', '', '', '', 'Micros', 'Ideas', '', 'Skytouch Technology', '', 'Choiceadvantage', 'Shangri-La Hotel, At The Shard, London', 'shangri-la.com', 'United Kingdom', '31 St Thomas St', 'London', '', 'SE1 9QU', '', 'Betty', 'Lau', 'Director of Sales and Marketing', 'betty.lau@shangri-la.com', '44 20 7234 8000', 202, 5, 'US$ 83 - US$ 141', 'Meeting Rooms', 'Chain Hotel', '', '', '', '', ''),
(34, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Synxis', 'Opera', '', 'MARSHA', 'AM Resorts', 'amresorts.com', 'United States', '7 Campus Blvd', 'Newtown Square', 'PA', '19073', '', 'Colette', 'Baruth', 'Senior Vice President - Sales, Marketing', 'cbaruth@amresorts.com', '1 610-359-6500', 406, 5, 'US$ 116 - US$ 230', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(35, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Trust International', 'Opera', '', 'MARSHA', 'Axiom Hotel', 'axiomhotel.com', 'United States', '28 Cyril Magnin St', 'San Francisco', 'CA', '94102', '', 'Garry', 'Cox', 'General Manager', 'garry.cox@axiomhotel.com', '1 415-392-9466', 252, 4, 'US$ 98 - US$ 217', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(36, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Checkfront', 'Opera', '', 'MARSHA', 'Belle of Baton Rouge Casino & Hotel', 'belleofbatonrouge.com', 'United States', '103 France St', 'Baton Rouge', 'LA', '70802', '', 'Erick', 'Andry', 'Director of Marketing', 'eandry@belleofbatonrouge.net', '1 225-242-2600', 67, 4, 'US$ 104 - US$ 301', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(37, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Navis Technology', 'Opera', '', 'MARSHA', 'Catamaran Resort Hotel and Spa', 'catamaranresort.com', 'United States', '3999 Mission Blvd', 'San Diego', 'CA', '92109', '', 'Mike', 'Staples', 'General Manager', 'mstaples@Catamaranresort.com', '1 858-488-1081', 136, 4, 'US$ 91 - US$ 218', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(38, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'MARSHA', 'Opera', '', 'MARSHA', 'Dream Inn', 'dreaminn.com', 'The USA', '3217 S Atlantic Ave', 'Daytona Beach Shores', 'FL', '32118', '', 'John', 'Kinberger', 'General Manager', 'Kinberger-John@dreaminn.com', '1 888-280-5260', 100, 4, 'US$ 87 - US$ 242', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(39, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Bookonthenet', 'Opera', '', 'MARSHA', 'Hawthorne Hotel', 'hawthornehotel.com', 'United States', '18 Washington Square W', 'Salem', 'MA', '1970', '', 'Claire', 'Kallelis', 'General Manager', 'ckallelis@hawthornehotel.com', '1 978-744-4080', 80, 3, 'US$ 89 - US$ 188', 'Restaurant & Meeting Room', 'Small Chain', '', '', '', '', ''),
(40, 'Opera PMS', '', 'Cendyn', '', 'Micros', 'One Yield', 'Amadeus', 'Opera', '', 'MARSHA', 'The Hayes Street Hotel & Bar', 'hayesstreethotel.com', 'United States', '1909 Hayes St', 'Nashville', 'TN', '37203', '', 'Katie', 'Ciammetti', 'General Manager', 'katie.ciammetti@hayesstreethotel.com', '1 615-320-0110', 98, 4, 'US$ 153 - US$ 220', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(41, 'Opera PMS', '', 'Cendyn', '', 'Micros', 'One Yield', 'Amadeus', 'Opera', '', 'MARSHA', 'Hotel ICON Ltd', 'hotel-icon.com', 'Hong Kong', '17 Science Museum Rd', 'Tsim Sha Tsui', '', '', '', 'Richard', 'Hatters', 'General manager', 'gm@hotel-icon.com', '852 3400 1000', 178, 5, 'US$ 76 - US$ 218', 'Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(42, 'Opera PMS', '', 'Cendyn', '', 'Micros', 'One Yield', 'Amadeus', 'Opera', '', 'MARSHA', 'Hotel del Coronado, Curio Collection by Hilton', 'hoteldel.com', 'USA', '1500 Orange Ave', 'Coronado', 'CA', '92118', '', 'Cheryl', 'Ferguson', 'Director of Sales', 'cheryl.ferguson@hoteldel.com', '1-619-435-6611', 165, 4, 'US$ 176 - US$ 371', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(43, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Amadeus', 'Opera', '', 'MARSHA', 'Inn at 500 Capitol', 'innat500.com', 'United States', '500 S Capitol Blvd', 'Boise', 'ID', '83702', '', 'Adam', 'Altwies', 'Asst. General Manager', 'aaltwies@innat500.com', '1 208-227-0500', 50, 3, 'US$ 132 - US$ 226', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(44, 'Opera PMS', '', 'Cendyn', '', 'Micros', 'One Yield', 'Amadeus', 'Opera', '', 'MARSHA', 'Inn at the 5th Eugene', 'innat5th.com', 'United States', '205 E 6th Ave', 'Eugene', 'OR', '97401', '', 'Nicole', 'Roselio', 'Director of Sales', 'nicole@obie.com', '1 541-743-4099', 130, 3, 'US$ 93 - US$ 205', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(45, 'Opera PMS', '', 'Cendyn', '', 'Micros', 'One Yield', 'MARSHA', 'Opera', '', 'MARSHA', 'Inn At Discovery Coast', 'innatdiscoverycoast.com', 'United States', '421 11th St SW', 'Long Beach', 'WA', '98631', '', 'Brady', 'Turner', 'Owner', 'brady@innatdiscoverycoast.com', '1 360-642-5265', 150, 4, 'US$ 109 - US$ 191', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(46, 'Opera PMS', '', 'Cendyn', '', 'Micros', 'One Yield', 'Windsurfer CRS', 'Opera', '', 'MARSHA', 'Aurora Inn', 'innsofaurora.com', 'United States', '391 Main St', 'Aurora', 'NY', '13026', '', 'Jodi', 'Bennett', 'General Manager', 'jbennett@innsofaurora.com', '1 315-364-8888', 141, 4, 'US$ 87 - US$ 187', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(47, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'Linden Row Inn', 'lindenrowinn.com', 'United States', '100 E Franklin St', 'Richmond', 'VA', '23219', '', 'Robin', 'Gonyea', 'General Manager', 'gm@lindenrowinn.com', '1 804-783-7000', 80, 5, 'US$ 96 - US$ 209', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(48, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'The Lodge at Jackson Hole', 'lodgeatjh.com', 'United States', '80 Scott Ln', 'Jackson', 'WY', '83002', '', 'Trey', 'Millard', 'Manager', 'trey@lodgeatjh.com', '1 307-739-9703', 141, 5, 'US$ 120 - US$ 234', 'Restaurant & Meeting Room', 'Chain Hotel', '', '', '', '', ''),
(49, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Travelclick', 'Opera', '', 'MARSHA', 'The Lodge at Torrey Pines', 'lodgetorreypines.com', 'United States', '11480 N Torrey Pines Rd, La Jolla', 'San Diego', 'CA', '92037', '', 'Bill', 'Gross', 'General Manager', 'bgross@lodgetorreypines.com', '1 858 453 4420', 141, 5, 'US$ 118 - US$ 179', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(50, '', '', 'Agile CRM', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'The Whitehall Hotel', 'thewhitehallhotel.com', 'United States', '105 E Delaware Pl', 'Chicago', 'IL', '60611', '', 'Troy', 'Strand', 'General Manager', 'tstrand@thewhitehallhotel.com', '312-944-6300', 222, 5, 'US$ 99 - US$ 171', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(51, '', '', 'Apptivo', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'The Visionaire Apartment Hotel In Lisbon', 'visionaireapartments.com', 'Portugal', 'Praça Da Figueira 5', 'Lisboa', '', '1100-240', '', 'Miguel', 'Fernandes', 'General Manager', 'manager@visionaireapartments.com', '351 912 769 797', 17, 4, 'US$ 145 - US$ 180', 'Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(52, '', '', 'Bitrix24', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'W Hotel Amsterdam, Netherlands', 'wamsterdam.nl', 'Netherlands', 'Spuistraat 175', 'Amsterdam', '', '1012 VN', '', 'Simone', 'Stevens', 'Director Of Revenue Management', 'simone.stevens@marriott.com', '31 20 811 2500', 238, 4, 'US$ 140 - US$ 259', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(53, '', '', 'Capsule', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'Hotel abdj de Westerburcht', 'westerburcht.nl', 'Netherlands', 'Hoofdstraat 7', 'Westerbork', '', '9431 AB', '', 'David', 'De Leeuw', 'General Manager', 'info@westerburcht.nl', '31 593 331 238', 37, 3, 'US$ 135 - US$ 164', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(54, '', '', 'Flowlu', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'The Whitehall Hotel Maine', 'whitehallmaine.com', 'United States', '52 High St', 'Camden', 'ME', '4843', '', 'Gwen', 'Clemens', 'General Manager', 'stay@whitehallmaine.com', '1 207-236-3391', 36, 4, 'US$ 110 - US$ 191', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(55, '', '', 'HubSpot CRM', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'Yasuragi', 'yasuragi.se', 'Sweden', 'Hamndalsvägen 6', 'Saltsjö-Boo', '', '132 39', '', 'Markus', 'Hellgren', 'Commercial Director', 'markus.hellgren@yasuragi.se', '46 8 747 61 00', 191, 4, 'US$ 100 - US$ 217', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(56, '', 'Opera PMS', 'Insightly', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'Valentin Paguera Adults Only', 'valentinhotels.com', 'Spain', 'Carrer Del Peral, 3', 'Peguera, Illes Balears', '', '7160', '', 'Alejo', 'Muñoz', 'Director', 'a.munoz@valentinhotels.com', '34 971 68 67 12', 200, 3, 'US$ 97 - US$ 321', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(57, '', 'Opera PMS', 'Really Simple Systems', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'Valentin Park Club Hotel & Aptos', 'valentinhotels.com/hoteles/valentin-park-club-hotel-apartamentos/', 'Spain', 'Carrer Eucaliptus, 20', 'Peguera, Illes Balears', '', '7160', '', 'Victor', 'Díaz', 'Director', 'v.diaz@valentinhotels.com', '34 971 03 20 22', 239, 4, 'US$ 150 - US$ 591', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(58, '', 'Opera PMS', 'Zoho CRM', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'Valentin Reina Paguera Adults Only', 'valentinhotels.com/hoteles/valentin-reina-paguera-hotel/', 'Spain', 'Carrer Mallorca, 1', 'Peguera, Illes Balears', '', '7160', '', 'Juan', 'Mulet', 'Director', 'j.mulet@valentinhotels.com', '34 971 68 63 50', 236, 4, 'US$ 170 - US$ 460', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(59, '', '', 'Agile CRM', '', 'Micros', 'Beonprice', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'Valentin Star Hotel Adults Only', 'valentinhotels.com/hoteles/valentin-star-hotel/', 'Spain', 'Carrer Del Port S/N Lago Cala\'N Bosch', 'Ciudadela, Islas Baleares', '', '7760', '', 'Juan', 'Dols', 'Director', 'j.dols@valentinhotels.com', '34 971 38 70 14', 208, 4, 'US$ 107 - US$ 149', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(60, '', 'Opera PMS', 'Apptivo', '', '', '', 'Choiceadvantage', 'Maestro', '', 'Synxis', 'Valentin Imperial Riviera Maya', 'valentinmaya.com', 'Mexico', 'Carretera Federal 307 Puerto Juarez Km 311', 'Playa Del Carmen', 'Q.R.', '77710', '', 'Vicente', 'Iglesias', 'General Manager', 'v.iglesias@valentinhotels.com', '52 984 206 3660', 540, 4, 'US$ 165 - US$ 240', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(61, '', 'Opera PMS', 'Bitrix24', '', 'Micros', 'Beonprice', 'Choiceadvantage', 'Opera', '', 'Amadeus', 'Valentin Sancti Petri', 'valentinsanctipetri.com', 'Spain', 'Av. Octavio Augusto, S/N', 'Urb. Novo Santi Petri', 'Cádiz', '11130', '', 'Miguel', 'Angel Mayol Barceló', 'Director', 'm.angel mayol barcelo@valentinhotels.com', '34 956 49 10 00', 549, 4, 'US$ 82 - US$ 182', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(62, '', 'Opera PMS', 'Bitrix24', '', '', 'Infor EzLITE revenue management system', 'Choiceadvantage', 'Sabre Hospitality', '', 'Synxis', '1 Hotel Brooklyn Bridge', '1hotels.com/brooklyn-bridge', 'United States', '60 Furman St', 'Brooklyn', 'NY', '11201', '', 'Hans', 'Schaepman', 'General Manager', 'hans.schaepman@1hotels.com', '1 347-696-2500', 194, 5, 'US$ 73 - US$ 115', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(63, '', '', 'Capsule', '', 'Micros', 'Infor EzLITE revenue management system', 'Choiceadvantage', 'Sabre Hospitality', '', 'Synxis', '1 Hotel Central Park', '1hotels.com/central-park', 'United States', '1414 6Th Ave', 'New York', 'NY', '10019', '', 'Nicholas', 'Farina', 'General Manager', 'nicholas.farina@1hotels.com', '1 212-703-2001', 229, 5, 'US$ 62 - US$ 84', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(64, '', 'Opera PMS', 'Flowlu', '', 'Micros', 'Duetto', 'Choiceadvantage', 'Opera', '', 'MARSHA', '1 Hotel South Beach', '1hotels.com/south-beach', 'The USA', '2341 Collins Ave', 'Miami Beach', 'FL', '33139', '', 'Fernando', 'Cerna', 'Director Of Sales & Marketing', 'fernando.cerna@1hotels.com', '1 833-625-3111', 426, 5, 'US$ 116 - US$ 230', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(65, '', 'Opera PMS', 'HubSpot CRM', '', 'Micros', 'Duetto', 'Choiceadvantage', 'Opera', '', 'MARSHA', '1 Hotel West Hollywood', '1hotels.com/west-hollywood', 'United States', '8490 Sunset Blvd', 'West Hollywood', 'CA', '90069', '', 'Tim', 'Flodin', 'General Manager', 'tim.flodin@1hotels.com', '1 310-424-1600', 285, 5, 'US$ 144 - US$ 248', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(66, '', 'Opera PMS', 'Insightly', '', 'Micros', 'Duetto', 'Choiceadvantage', 'Opera', '', 'OnQ', 'Abba Fonseca Hotel', 'abbahoteles.com/en/destinations/abba-fonseca-hotel', 'Spain', 'Plaza De San Blas, 2', 'Salamanca', '', '37007', '', 'Itxaso', 'Aguirre', 'General Manager', 'fonseca@abbahoteles.com', '34 923 01 10 10', 86, 4, 'US$ 125 - US$ 272', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(67, '', '', 'Really Simple Systems', '', 'Micros', 'Duetto', 'Choiceadvantage', 'Opera', '', 'OnQ', 'Ace Hotel London', 'acehotel.com/london', 'Uk', '100 Shoreditch High St', 'Hackney', 'London', 'E1 6JQ', '', 'Jose', 'Piquer', 'Front Office Manager', 'jose.piquer@acehotel.com', '44 20 7613 9800', 258, 4, 'US$ 112 - US$ 253', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(68, '', 'Opera PMS', 'Zoho CRM', '', 'Micros', 'Ideas', 'Choiceadvantage', 'Snapshot', '', 'OnQ', 'Azimut Hotel Murmansk', 'azimuthotels.com/Russia/azimut-hotel-murmansk/', 'Russia', 'Prospekt Lenina, 82', 'Murmansk', '', '183038', '', 'Andrew', 'Sakin', 'General Manager', 'asakin@azimuthotels.com', '7 815 255-03-50', 36, 4, 'US$ 76 - US$ 208', 'Restaurant & Meeting Room', 'Chain Hotel', '', '', '', '', ''),
(69, '', 'Opera PMS', 'Agile CRM', '', 'Micros', 'Ideas', 'Choiceadvantage', 'Snapshot', '', 'OnQ', 'Azimut Hotel Nizhny Novgorod', 'azimuthotels.com/Russia/azimut-hotel-nizhny-novgorod/', 'Russia', 'Ulitsa Zalomova, 2', 'Nizhny Novgorod Oblast', '', '603109', '', 'Olga', 'Bruns', 'General Manager', 'obruns@azimuthotels.com', '7 831 461-92-42', 191, 5, 'US$ 121 - US$ 301', 'Restaurant & Meeting Room', 'Chain Hotel', '', '', '', '', ''),
(70, '', 'Opera PMS', 'Apptivo', '', 'Micros', 'Ideas', 'Choiceadvantage', 'Opera', '', 'OnQ', 'Azimut Hotel Pereslavl', 'azimuthotels.com/Russia/azimut-hotel-pereslavl/', 'Russia', 'Ulitsa Okruzhnaya, 29А', 'Rostov', '', '152151', '', 'Julia', 'Khrustaleva', 'General Manager', 'jkhrustaleva@azimuthotels.de', '7 495 272-01-40', 200, 5, 'US$ 94 - US$ 272', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(71, '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '17', '13', '14', '15', '16', 'mr', 'vishal', 'mangade', 'admin', '', '23', 24, 25, '26', '27', '28', '29', '30', '31', '32', '33'),
(72, '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '17', '13', '14', '15', '16', '18', '19', '20', '21', '22', '23', 24, 25, '26', '27', '28', '29', '30', '31', '32', '33'),
(73, '', 'Opera PMS', '', '', '', '', '', 'Opera PMS', '', 'Windsurfer CRS', 'Amba Hotel Charing Cross', 'amba-hotel.com', 'United Kingdom', 'Strand', 'London', '', 'WC2N 5HX', '', 'Pedro', 'Da Silva', 'General Manager', 'pedro.dasilva@amba-hotel.com', '44 800 330 8397', 239, 4, 'US$ 198 - US$ 1,051', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(74, '', 'Guestline PMS', '', '', 'Micros', 'One Yield', '', 'Opera PMS', '', 'MARSHA', 'Ambassadors Bloomsbury', 'ambassadors.co.uk', 'United Kingdom', '12 Upper Woburn Pl, Bloomsbury', 'London', '', 'WC1H 0HX', '', 'Johny', 'Jones', 'General Manager', 'generalmanager@ambassadors.co.uk', '44 20 7693 5400', 100, 4, 'US$ 97 - US$ 215', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(75, 'Opera PMS', 'Opera PMS', '', '', 'Micros', 'One Yield', '', 'Opera PMS', '', 'MARSHA', 'The Ampersand Hotel', 'ampersandhotel.com', 'United Kingdom', '10 Harrington Rd, Kensington', 'London', '', 'SW7 3ER', '', 'Roberto', 'Pajares', 'General Manager', 'rp@ampersandhotel.com', '44 20 7589 5895', 111, 5, 'US$ 120 - US$ 174', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(76, 'Opera PMS', 'Opera PMS', '', '', '', '', '', 'Guestline PMS', '', 'Reseze', 'Antoinette Hotel', 'antoinettehotel.com', 'United Kingdom', 'The Broadway', 'London', '', 'SW19 1SD', '', 'Francesco', 'Bartolomei', 'General Manager', 'francescob@antoinettehotels.com', '442000000000', 100, 3, 'US$ 105 - US$ 344', 'Meeting Rooms', 'Indepedent hotel', '', '', '', '', ''),
(77, 'Opera PMS', 'Opera PMS', '', '', '', '', '', 'Opera PMS', '', 'Booking.com', 'The Athenaeum Hotel', 'athenaeumhotel.com', 'United Kingdom', '116 Piccadilly, Mayfair', 'London', '', 'W1J 7BJ', '', 'Jeremy', 'Hopkins', 'General Manager', 'hopkinsj@athenaeumhotel.com', '44 20-7499-3464', 164, 5, 'Not Available', 'None', 'Independent hotel', '', '', '', '', ''),
(78, '', 'Opera PMS', '', '', 'Micros', 'Infor EzLITE revenue management system', '', 'Opera PMS', '', 'Synxis', 'Baglioni Hotel London', 'baglionihotels.com', 'United Kingdom', '60 Hyde Park Gate, Kensington', 'London', '', 'SW7 5BB', '', 'Alessandro', 'Convertino', 'General Manager', 'a.convertino@baglionihotels.com', '44 20-7368-5700', 67, 5, 'US$ 75 - US$ 155', 'Meeting Room', 'Small Chain', '', '', '', '', ''),
(79, 'Opera PMS', '', '', '', 'Micros', 'Infor EzLITE revenue management system', '', 'Opera PMS', '', 'Synxis', 'Bayswater Inn Hotel', 'bayswaterinnhotel.com', 'United Kingdom', '16 Prince\'s Square', 'London', '', 'W2 4NT', '', 'David', 'Gesto', 'Cluster General Manager', 'david.gesto@bayswaterinnhotel.com', '44 20 7727 8621', 140, 3, 'US$ 86 - US$ 109', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(80, 'Opera PMS', '', '', '', 'Micros', 'Infor EzLITE revenue management system', '', 'Opera PMS', '', 'Synxis', 'Hotel Berjaya Eden Park London', 'berjayahotel.com', 'United Kingdom', '35-39 Inverness Terrace', 'London', '', 'W2 3JS', '', 'Kathleen', 'Tay', 'General Manager', 'gm.london@berjayahotel.com', '44 20 7221 2220', 114, 3, 'US$ 63 - US$ 98', 'Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(81, 'Opera PMS', '', '', '', '', '', '', 'Opera PMS', '', 'Trust International', 'Blakemore Hyde Park Hotel', 'blakemorehydepark.com', 'United Kingdom', '30 Leinster Gardens', 'London', '', 'W2 3AN', '', 'Pradeep', 'Gurtata', 'General Manager', 'pradeep.gurtata@starcrown.com', '442000000000', 164, 4, 'US$ 136 - US$ 390', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(82, '', '', '', '', '', '', '', 'Guestline PMS', '', 'Checkfront', 'The Bromley Court Hotel', 'bromleycourthotel.co.uk', 'United Kingdom', 'Bromley Hill, Bromley', 'London', '', 'BR1 4JD', '', 'Graham', 'Rothwell', 'General Manager', 'g.rothwell@bromleycourthotel.co.uk', '442000000000', 117, 3, 'US$ 120 - US$ 169', 'Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(83, 'Opera PMS', 'Opera PMS', '', '', '', '', '', 'Opera PMS', '', 'Navis Technology', 'Central Park Hotel', 'centralparklondon.co.uk', 'United Kingdom', '49-67 Queensborough Terrace', 'London', '', 'W2 3SY', '', 'Angelika', 'Meltzer', 'General Manager', 'angelika.meltzer@centralparklondon.co.uk', '442000000000', 295, 3, 'US$ 172 - US$ 369', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(84, 'Opera PMS', 'Opera PMS', '', '', 'Micros', 'One Yield', '', 'Opera PMS', '', 'MARSHA', 'The Clarendon Hotel', 'clarendonhotel.com', 'United Kingdom', '8-16 Montpelier Row, Blackheath', 'London', '', 'SE3 0RW', '', 'Ken', 'Milton', 'General Manager', 'ken@clarendonhotel.com', '44 208 318 4321', 180, 3, 'US$ 150 - US$ 591', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(85, 'Opera PMS', 'Opera PMS', '', '', '', '', '', 'Opera PMS', '', 'Bookonthenet', 'Claridge`S Hotel', 'claridges.co.uk', 'United Kingdom', 'Brook St, Mayfair', 'London', '', 'W1K 4HR', '', 'Paul', 'Jackson', 'General Manager', 'pjackson@claridges.co.uk', '442000000000', 190, 5, 'US$ 93 - US$ 120', 'Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(86, '', '', '', '', 'Micros', 'IDeas', 'Choiceadvantage', 'Brilliant PMS (Amadeus)', '', 'Amadeus', 'Goodenough Club', 'club.goodenough.ac.uk', 'United Kingdom', '23 Mecklenburgh Square', 'London', '', 'WC1N 2AD', '', 'Louise', 'O\'Gorman', 'General Manager', 'louise.o\'gorman@goodenough.ac.uk', '44 20 7837 8831', 63, 4, 'US$ 91 - US$ 124', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(87, '', 'Opera PMS', '', '', 'Micros', 'IDeas', 'Choiceadvantage', 'Opera PMS', '', 'Amadeus', 'Corinthia Hotel London', 'corinthia.com', 'United Kingdom', 'Whitehall Pl, Westminster', 'London', '', 'SW1A 2BD', '', 'Matthew', 'Dixon', 'General Manager', 'matthew.dixon@corinthia.com', '44 20-7930-8181', 294, 5, 'US$ 83 - US$ 141', 'Meeting Rooms', 'Chain Hotel', '', '', '', '', ''),
(88, '', 'Opera PMS', '', '', 'Micros', 'IDeas', 'Choiceadvantage', 'Opera PMS', '', 'Amadeus', 'The Courthouse Hotel', 'courthouse-hotel.com', 'United Kingdom', '19 - 21 Great Marlborough St, Soho', 'London', '', 'W1F 7HL', '', 'Roy', 'Sommer', 'General Manager', 'roy.sommer@courthouse-hotel.com', '442000000000', 112, 5, 'US$ 93 - US$ 240', 'Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(89, '', 'Opera PMS', '', '', 'Micros', 'IDeas', 'Curtis - C', 'Opera PMS', '', 'Amadeus', 'Dolphin House Serviced Apartments', 'dolphinsquare.co.uk', 'United Kingdom', 'Dolphin Square, Chichester St, Pimlico', 'London', '', 'SW1V 3LX', '', 'Neil', 'Miller-Chalk', 'General Manager', 'nmchalk@dolphinsquare.co.uk', '44 20 7798 8000', 165, 4, 'US$ 97 - US$ 199', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(90, '', '', '', '', 'Micros', 'IDeas', 'Curtis - C', 'Opera PMS', '', 'Amadeus', 'Durrants Hotel', 'durrantshotel.co.uk', 'United Kingdom', '32 George St, Marylebone', 'London', '', 'W1H 5BJ', '', 'Ian', 'McIntosh', 'General Manager', 'ian.mcintosh@durrantshotel.co.uk', '44 20 7935 8131', 92, 4, 'US$ 99 - US$ 129', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(91, '', 'Opera PMS', '', '', 'Micros', 'One Yield', 'Curtis - C', 'Mews', '', 'MARSHA', 'Hotel Euston Square', 'euston-square-hotel.com', 'United Kingdom', '152-156 North Gower Street', 'London', '', 'NW1 2LU', '', 'Navin', 'Silwal', 'General Manager', 'navin.sillwal@euston-square-hotel.com', '44 20 7388 0099', 75, 3, 'US$ 239 - US$ 748', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(92, '', 'Opera PMS', '', '', '', '', 'Curtis - C', 'Opera PMS', '', 'Windsurfer CRS', 'Flemings Mayfair Hotel', 'flemings.co.uk', 'United Kingdom', '7-12 Half Moon St, Mayfair', 'London', '', 'W1J 7BH', '', 'Henrik', 'Muehle', 'General Manager', 'henrik.muehle@flemings.co.uk', '44 20-7499-0000', 129, 4, 'US$ 66 - US$ 122', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(93, '', 'Opera PMS', '', '', 'Micros', 'Ideas', 'Curtis - C', 'Mews', '', 'Choiceadvantage', 'Grand Plaza Serviced Apartment Hotel', 'grand-plaza.co.uk', 'United Kingdom', '42 Prince\'s Square', 'London', '', 'W2 4AD', '', 'Mohd', 'Jeffri', 'Chief Executive Officer', 'mohd.jeffri@grandplazaemail.co.uk', '44 20-7985-8000', 198, 4, 'US$ 85 - US$ 166', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(94, 'Opera PMS', '', '', '', 'Micros', 'Ideas', '', 'Mews', '', 'Choiceadvantage', 'The Park City Grand Plaza Kensington Hotel', 'parkcitylondon.com', 'United Kingdom', '18-30 Lexham Gardens, Kensington', 'London', '', 'W8 5JE', '', 'Alessandro', 'D\'Ambrosio', 'Front Desk Manager', 'alessandro@parkcitylondon.co.uk', '44 20 7341 7090', 62, 4, 'US$ 90 - US$ 144', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(95, 'Opera PMS', '', '', '', 'Micros', 'Ideas', '', 'Opera PMS', '', 'Choiceadvantage', 'Park International Hotel', 'parkinternationalhotel.com', 'United Kingdom', '117-129 Cromwell Rd, Kensington', 'London', '', 'SW7 4DS', '', 'Aflal', 'Jabir', 'Operations Manager', 'aflal.jabir@parkinternationalhotel.com', '44 20 7370 5711', 171, 4, 'US$ 91 - US$ 138', 'Meeting Room', 'Small Chain', '', '', '', '', ''),
(96, 'Opera PMS', '', '', '', 'Micros', 'Ideas', '', 'Opera PMS', '', 'Choiceadvantage', 'Royal Garden Hotel', 'royalgardenhotel.co.uk', 'United Kingdom', '2-24 Kensington High St, Kensington', 'London', '', 'W8 4PT', '', 'Mark', 'Anderson', 'Director of Sales and Marketing', 'markanderson@royalgardenhotel.co.uk', '44 20-7937-8000', 394, 5, 'US$ 83 - US$ 134', 'Meeting Rooms', 'Independent hotel', '', '', '', '', ''),
(97, '', 'Opera PMS', '', '', 'Micros', 'Ideas', '', 'Visual One', '', 'Choiceadvantage', 'Royal Garden Hotel', 'royalgardenhotel.co.uk', 'United Kingdom', '2-24 Kensington High St ,Kensington', 'London', '', 'W8 4PT', '', 'Sian', 'Walker', 'Marketing Manager', 'SianWalker@royalgardenhotel.co.uk', '44 0 20 7937 8000', 394, 5, 'US$ 78 - US$ 120', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(98, 'Opera PMS', 'Opera PMS', '', '', 'Micros', 'Ideas', '', 'Visual One', '', 'Choiceadvantage', 'Royal Garden Hotel', 'royalgardenhotel.co.uk', 'United Kingdom', '2-24 Kensington High St ,Kensington', 'London', '', 'W8 4PT', '', 'Oliver', 'Bateman', 'General Manager', 'OliverBateman@royalgardenhotel.co.uk', '44 0 20 7937 8000', 394, 5, 'US$ 81 - US$ 173', 'NONE', 'Independent hotel', '', '', '', '', ''),
(99, 'Opera PMS', 'Opera PMS', '', '', 'Micros', 'Ideas', '', 'Skytouch Technology', '', 'Choiceadvantage', 'Royal Garden Hotel', 'royalgardenhotel.co.uk', 'United Kingdom', '2-24 Kensington High St, Kensington', 'London', '', 'W8 4PT', '', 'Tim', 'Fryer', 'Deputy General Manager - Operations', 'timfryer@royalgardenhotel.co.uk', '44 20-7937-8000', 394, 5, 'US$ 101 - US$ 179', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(100, 'Opera PMS', '', '', '', 'Micros', 'Ideas', '', 'Skytouch Technology', '', 'Choiceadvantage', 'Royal Garden Hotel', 'royalgardenhotel.co.uk', 'United Kingdom', '24 Kensington High Street', 'London', '', 'W8 5', '', 'Oliver', 'Bateman', 'General Manager', 'obateman@royalgardenhotel.co.uk', '44 0 20 7937 8000', 394, 5, 'US$ 88 - US$ 147', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(101, '', 'Opera PMS', '', '', 'Micros', 'Ideas', '', 'Skytouch Technology', '', 'Choiceadvantage', 'Royal Garden Hotel', 'royalgardenhotel.co.uk', 'United Kingdom', '24 Kensington High Street', 'London', '', 'W8 5', '', 'Sian', 'Walker', 'Marketing Manager', 'swalker@royalgardenhotel.co.uk', '44 0 20 7937 8000', 394, 5, 'US$ 122 - US$ 400', 'Meeting Rooms', 'Independent hotel', '', '', '', '', ''),
(102, 'Opera PMS', 'Opera PMS', '', '', 'Micros', 'Ideas', '', 'Skytouch Technology', '', 'Choiceadvantage', 'Royal Lancaster London', 'royallancaster.com', 'United Kingdom', 'Lancaster Terrace', 'London', '', 'W2 2TY', '', 'Sally', 'Beck', 'General Manager', 'seb@lancasterlondon.com', '44 20 7551 6000', 416, 4, 'US$ 110 - US$ 318', 'Meeting Rooms', 'Independent hotel', '', '', '', '', ''),
(103, 'Opera PMS', 'Opera PMS', '', '', 'Micros', 'Ideas', '', 'Skytouch Technology', '', 'Choiceadvantage', 'Sarova Hotels Ltd', 'sarova.com', 'United Kingdom', '11 Thurloe Cl, Kensington', 'London', '', 'SW7 2RS', '', 'Karl', 'Wilson', 'General Manager', 'kwilson@sarova.com', '44 20 7589 5151', 194, 4, 'US$ 74 - US$ 140', 'Meeting Room', 'Chain Hotel', '', '', '', '', ''),
(104, 'Opera PMS', '', '', '', 'Micros', 'Ideas', '', 'Skytouch Technology', '', 'Choiceadvantage', 'Shangri-La Hotel, At The Shard, London', 'shangri-la.com', 'United Kingdom', '31 St Thomas St', 'London', '', 'SE1 9QU', '', 'Betty', 'Lau', 'Director of Sales and Marketing', 'betty.lau@shangri-la.com', '44 20 7234 8000', 202, 5, 'US$ 83 - US$ 141', 'Meeting Rooms', 'Chain Hotel', '', '', '', '', ''),
(105, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Synxis', 'Opera', '', 'MARSHA', 'AM Resorts', 'amresorts.com', 'United States', '7 Campus Blvd', 'Newtown Square', 'PA', '19073', '', 'Colette', 'Baruth', 'Senior Vice President - Sales, Marketing', 'cbaruth@amresorts.com', '1 610-359-6500', 406, 5, 'US$ 116 - US$ 230', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(106, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Trust International', 'Opera', '', 'MARSHA', 'Axiom Hotel', 'axiomhotel.com', 'United States', '28 Cyril Magnin St', 'San Francisco', 'CA', '94102', '', 'Garry', 'Cox', 'General Manager', 'garry.cox@axiomhotel.com', '1 415-392-9466', 252, 4, 'US$ 98 - US$ 217', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(107, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Checkfront', 'Opera', '', 'MARSHA', 'Belle of Baton Rouge Casino & Hotel', 'belleofbatonrouge.com', 'United States', '103 France St', 'Baton Rouge', 'LA', '70802', '', 'Erick', 'Andry', 'Director of Marketing', 'eandry@belleofbatonrouge.net', '1 225-242-2600', 67, 4, 'US$ 104 - US$ 301', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(108, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Navis Technology', 'Opera', '', 'MARSHA', 'Catamaran Resort Hotel and Spa', 'catamaranresort.com', 'United States', '3999 Mission Blvd', 'San Diego', 'CA', '92109', '', 'Mike', 'Staples', 'General Manager', 'mstaples@Catamaranresort.com', '1 858-488-1081', 136, 4, 'US$ 91 - US$ 218', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(109, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'MARSHA', 'Opera', '', 'MARSHA', 'Dream Inn', 'dreaminn.com', 'The USA', '3217 S Atlantic Ave', 'Daytona Beach Shores', 'FL', '32118', '', 'John', 'Kinberger', 'General Manager', 'Kinberger-John@dreaminn.com', '1 888-280-5260', 100, 4, 'US$ 87 - US$ 242', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(110, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Bookonthenet', 'Opera', '', 'MARSHA', 'Hawthorne Hotel', 'hawthornehotel.com', 'United States', '18 Washington Square W', 'Salem', 'MA', '1970', '', 'Claire', 'Kallelis', 'General Manager', 'ckallelis@hawthornehotel.com', '1 978-744-4080', 80, 3, 'US$ 89 - US$ 188', 'Restaurant & Meeting Room', 'Small Chain', '', '', '', '', ''),
(111, 'Opera PMS', '', 'Cendyn', '', 'Micros', 'One Yield', 'Amadeus', 'Opera', '', 'MARSHA', 'The Hayes Street Hotel & Bar', 'hayesstreethotel.com', 'United States', '1909 Hayes St', 'Nashville', 'TN', '37203', '', 'Katie', 'Ciammetti', 'General Manager', 'katie.ciammetti@hayesstreethotel.com', '1 615-320-0110', 98, 4, 'US$ 153 - US$ 220', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(112, 'Opera PMS', '', 'Cendyn', '', 'Micros', 'One Yield', 'Amadeus', 'Opera', '', 'MARSHA', 'Hotel ICON Ltd', 'hotel-icon.com', 'Hong Kong', '17 Science Museum Rd', 'Tsim Sha Tsui', '', '', '', 'Richard', 'Hatters', 'General manager', 'gm@hotel-icon.com', '852 3400 1000', 178, 5, 'US$ 76 - US$ 218', 'Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(113, 'Opera PMS', '', 'Cendyn', '', 'Micros', 'One Yield', 'Amadeus', 'Opera', '', 'MARSHA', 'Hotel del Coronado, Curio Collection by Hilton', 'hoteldel.com', 'USA', '1500 Orange Ave', 'Coronado', 'CA', '92118', '', 'Cheryl', 'Ferguson', 'Director of Sales', 'cheryl.ferguson@hoteldel.com', '1-619-435-6611', 165, 4, 'US$ 176 - US$ 371', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(114, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Amadeus', 'Opera', '', 'MARSHA', 'Inn at 500 Capitol', 'innat500.com', 'United States', '500 S Capitol Blvd', 'Boise', 'ID', '83702', '', 'Adam', 'Altwies', 'Asst. General Manager', 'aaltwies@innat500.com', '1 208-227-0500', 50, 3, 'US$ 132 - US$ 226', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(115, 'Opera PMS', '', 'Cendyn', '', 'Micros', 'One Yield', 'Amadeus', 'Opera', '', 'MARSHA', 'Inn at the 5th Eugene', 'innat5th.com', 'United States', '205 E 6th Ave', 'Eugene', 'OR', '97401', '', 'Nicole', 'Roselio', 'Director of Sales', 'nicole@obie.com', '1 541-743-4099', 130, 3, 'US$ 93 - US$ 205', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(116, 'Opera PMS', '', 'Cendyn', '', 'Micros', 'One Yield', 'MARSHA', 'Opera', '', 'MARSHA', 'Inn At Discovery Coast', 'innatdiscoverycoast.com', 'United States', '421 11th St SW', 'Long Beach', 'WA', '98631', '', 'Brady', 'Turner', 'Owner', 'brady@innatdiscoverycoast.com', '1 360-642-5265', 150, 4, 'US$ 109 - US$ 191', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(117, 'Opera PMS', '', 'Cendyn', '', 'Micros', 'One Yield', 'Windsurfer CRS', 'Opera', '', 'MARSHA', 'Aurora Inn', 'innsofaurora.com', 'United States', '391 Main St', 'Aurora', 'NY', '13026', '', 'Jodi', 'Bennett', 'General Manager', 'jbennett@innsofaurora.com', '1 315-364-8888', 141, 4, 'US$ 87 - US$ 187', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(118, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'Linden Row Inn', 'lindenrowinn.com', 'United States', '100 E Franklin St', 'Richmond', 'VA', '23219', '', 'Robin', 'Gonyea', 'General Manager', 'gm@lindenrowinn.com', '1 804-783-7000', 80, 5, 'US$ 96 - US$ 209', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(119, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'The Lodge at Jackson Hole', 'lodgeatjh.com', 'United States', '80 Scott Ln', 'Jackson', 'WY', '83002', '', 'Trey', 'Millard', 'Manager', 'trey@lodgeatjh.com', '1 307-739-9703', 141, 5, 'US$ 120 - US$ 234', 'Restaurant & Meeting Room', 'Chain Hotel', '', '', '', '', ''),
(120, '', '', 'Cendyn', '', 'Micros', 'One Yield', 'Travelclick', 'Opera', '', 'MARSHA', 'The Lodge at Torrey Pines', 'lodgetorreypines.com', 'United States', '11480 N Torrey Pines Rd, La Jolla', 'San Diego', 'CA', '92037', '', 'Bill', 'Gross', 'General Manager', 'bgross@lodgetorreypines.com', '1 858 453 4420', 141, 5, 'US$ 118 - US$ 179', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(121, '', '', 'Agile CRM', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'The Whitehall Hotel', 'thewhitehallhotel.com', 'United States', '105 E Delaware Pl', 'Chicago', 'IL', '60611', '', 'Troy', 'Strand', 'General Manager', 'tstrand@thewhitehallhotel.com', '312-944-6300', 222, 5, 'US$ 99 - US$ 171', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(122, '', '', 'Apptivo', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'The Visionaire Apartment Hotel In Lisbon', 'visionaireapartments.com', 'Portugal', 'Praça Da Figueira 5', 'Lisboa', '', '1100-240', '', 'Miguel', 'Fernandes', 'General Manager', 'manager@visionaireapartments.com', '351 912 769 797', 17, 4, 'US$ 145 - US$ 180', 'Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(123, '', '', 'Bitrix24', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'W Hotel Amsterdam, Netherlands', 'wamsterdam.nl', 'Netherlands', 'Spuistraat 175', 'Amsterdam', '', '1012 VN', '', 'Simone', 'Stevens', 'Director Of Revenue Management', 'simone.stevens@marriott.com', '31 20 811 2500', 238, 4, 'US$ 140 - US$ 259', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(124, '', '', 'Capsule', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'Hotel abdj de Westerburcht', 'westerburcht.nl', 'Netherlands', 'Hoofdstraat 7', 'Westerbork', '', '9431 AB', '', 'David', 'De Leeuw', 'General Manager', 'info@westerburcht.nl', '31 593 331 238', 37, 3, 'US$ 135 - US$ 164', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(125, '', '', 'Flowlu', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'The Whitehall Hotel Maine', 'whitehallmaine.com', 'United States', '52 High St', 'Camden', 'ME', '4843', '', 'Gwen', 'Clemens', 'General Manager', 'stay@whitehallmaine.com', '1 207-236-3391', 36, 4, 'US$ 110 - US$ 191', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(126, '', '', 'HubSpot CRM', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'Yasuragi', 'yasuragi.se', 'Sweden', 'Hamndalsvägen 6', 'Saltsjö-Boo', '', '132 39', '', 'Markus', 'Hellgren', 'Commercial Director', 'markus.hellgren@yasuragi.se', '46 8 747 61 00', 191, 4, 'US$ 100 - US$ 217', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', '');
INSERT INTO `hotel` (`data_id`, `hrms`, `ats`, `crm`, `erp`, `pos`, `rms`, `cm`, `pms`, `ibe`, `crs`, `hotel_name`, `website`, `country`, `street`, `city`, `state`, `zipcode`, `prefix`, `first_name`, `last_name`, `title`, `email`, `contact_number`, `number_of_rooms`, `hotel_class`, `adr`, `services`, `type_of_hotel`, `ownership`, `chain_name`, `facebook_url`, `alexa_rank`, `monthly_visitor`) VALUES
(127, '', 'Opera PMS', 'Insightly', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'Valentin Paguera Adults Only', 'valentinhotels.com', 'Spain', 'Carrer Del Peral, 3', 'Peguera, Illes Balears', '', '7160', '', 'Alejo', 'Muñoz', 'Director', 'a.munoz@valentinhotels.com', '34 971 68 67 12', 200, 3, 'US$ 97 - US$ 321', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(128, '', 'Opera PMS', 'Really Simple Systems', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'Valentin Park Club Hotel & Aptos', 'valentinhotels.com/hoteles/valentin-park-club-hotel-apartamentos/', 'Spain', 'Carrer Eucaliptus, 20', 'Peguera, Illes Balears', '', '7160', '', 'Victor', 'Díaz', 'Director', 'v.diaz@valentinhotels.com', '34 971 03 20 22', 239, 4, 'US$ 150 - US$ 591', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(129, '', 'Opera PMS', 'Zoho CRM', '', 'Micros', 'One Yield', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'Valentin Reina Paguera Adults Only', 'valentinhotels.com/hoteles/valentin-reina-paguera-hotel/', 'Spain', 'Carrer Mallorca, 1', 'Peguera, Illes Balears', '', '7160', '', 'Juan', 'Mulet', 'Director', 'j.mulet@valentinhotels.com', '34 971 68 63 50', 236, 4, 'US$ 170 - US$ 460', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(130, '', '', 'Agile CRM', '', 'Micros', 'Beonprice', 'Choiceadvantage', 'Opera', '', 'MARSHA', 'Valentin Star Hotel Adults Only', 'valentinhotels.com/hoteles/valentin-star-hotel/', 'Spain', 'Carrer Del Port S/N Lago Cala\'N Bosch', 'Ciudadela, Islas Baleares', '', '7760', '', 'Juan', 'Dols', 'Director', 'j.dols@valentinhotels.com', '34 971 38 70 14', 208, 4, 'US$ 107 - US$ 149', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(131, '', 'Opera PMS', 'Apptivo', '', '', '', 'Choiceadvantage', 'Maestro', '', 'Synxis', 'Valentin Imperial Riviera Maya', 'valentinmaya.com', 'Mexico', 'Carretera Federal 307 Puerto Juarez Km 311', 'Playa Del Carmen', 'Q.R.', '77710', '', 'Vicente', 'Iglesias', 'General Manager', 'v.iglesias@valentinhotels.com', '52 984 206 3660', 540, 4, 'US$ 165 - US$ 240', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(132, '', 'Opera PMS', 'Bitrix24', '', 'Micros', 'Beonprice', 'Choiceadvantage', 'Opera', '', 'Amadeus', 'Valentin Sancti Petri', 'valentinsanctipetri.com', 'Spain', 'Av. Octavio Augusto, S/N', 'Urb. Novo Santi Petri', 'Cádiz', '11130', '', 'Miguel', 'Angel Mayol Barceló', 'Director', 'm.angel mayol barcelo@valentinhotels.com', '34 956 49 10 00', 549, 4, 'US$ 82 - US$ 182', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', ''),
(133, '', 'Opera PMS', 'Bitrix24', '', '', 'Infor EzLITE revenue management system', 'Choiceadvantage', 'Sabre Hospitality', '', 'Synxis', '1 Hotel Brooklyn Bridge', '1hotels.com/brooklyn-bridge', 'United States', '60 Furman St', 'Brooklyn', 'NY', '11201', '', 'Hans', 'Schaepman', 'General Manager', 'hans.schaepman@1hotels.com', '1 347-696-2500', 194, 5, 'US$ 73 - US$ 115', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(134, '', '', 'Capsule', '', 'Micros', 'Infor EzLITE revenue management system', 'Choiceadvantage', 'Sabre Hospitality', '', 'Synxis', '1 Hotel Central Park', '1hotels.com/central-park', 'United States', '1414 6Th Ave', 'New York', 'NY', '10019', '', 'Nicholas', 'Farina', 'General Manager', 'nicholas.farina@1hotels.com', '1 212-703-2001', 229, 5, 'US$ 62 - US$ 84', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(135, '', 'Opera PMS', 'Flowlu', '', 'Micros', 'Duetto', 'Choiceadvantage', 'Opera', '', 'MARSHA', '1 Hotel South Beach', '1hotels.com/south-beach', 'The USA', '2341 Collins Ave', 'Miami Beach', 'FL', '33139', '', 'Fernando', 'Cerna', 'Director Of Sales & Marketing', 'fernando.cerna@1hotels.com', '1 833-625-3111', 426, 5, 'US$ 116 - US$ 230', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(136, '', 'Opera PMS', 'HubSpot CRM', '', 'Micros', 'Duetto', 'Choiceadvantage', 'Opera', '', 'MARSHA', '1 Hotel West Hollywood', '1hotels.com/west-hollywood', 'United States', '8490 Sunset Blvd', 'West Hollywood', 'CA', '90069', '', 'Tim', 'Flodin', 'General Manager', 'tim.flodin@1hotels.com', '1 310-424-1600', 285, 5, 'US$ 144 - US$ 248', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(137, '', 'Opera PMS', 'Insightly', '', 'Micros', 'Duetto', 'Choiceadvantage', 'Opera', '', 'OnQ', 'Abba Fonseca Hotel', 'abbahoteles.com/en/destinations/abba-fonseca-hotel', 'Spain', 'Plaza De San Blas, 2', 'Salamanca', '', '37007', '', 'Itxaso', 'Aguirre', 'General Manager', 'fonseca@abbahoteles.com', '34 923 01 10 10', 86, 4, 'US$ 125 - US$ 272', 'Restaurant & Meeting Room', 'Independent hotel', '', '', '', '', ''),
(138, '', '', 'Really Simple Systems', '', 'Micros', 'Duetto', 'Choiceadvantage', 'Opera', '', 'OnQ', 'Ace Hotel London', 'acehotel.com/london', 'Uk', '100 Shoreditch High St', 'Hackney', 'London', 'E1 6JQ', '', 'Jose', 'Piquer', 'Front Office Manager', 'jose.piquer@acehotel.com', '44 20 7613 9800', 258, 4, 'US$ 112 - US$ 253', 'Meeting Room', 'Independent hotel', '', '', '', '', ''),
(139, '', 'Opera PMS', 'Zoho CRM', '', 'Micros', 'Ideas', 'Choiceadvantage', 'Snapshot', '', 'OnQ', 'Azimut Hotel Murmansk', 'azimuthotels.com/Russia/azimut-hotel-murmansk/', 'Russia', 'Prospekt Lenina, 82', 'Murmansk', '', '183038', '', 'Andrew', 'Sakin', 'General Manager', 'asakin@azimuthotels.com', '7 815 255-03-50', 36, 4, 'US$ 76 - US$ 208', 'Restaurant & Meeting Room', 'Chain Hotel', '', '', '', '', ''),
(140, '', 'Opera PMS', 'Agile CRM', '', 'Micros', 'Ideas', 'Choiceadvantage', 'Snapshot', '', 'OnQ', 'Azimut Hotel Nizhny Novgorod', 'azimuthotels.com/Russia/azimut-hotel-nizhny-novgorod/', 'Russia', 'Ulitsa Zalomova, 2', 'Nizhny Novgorod Oblast', '', '603109', '', 'Olga', 'Bruns', 'General Manager', 'obruns@azimuthotels.com', '7 831 461-92-42', 191, 5, 'US$ 121 - US$ 301', 'Restaurant & Meeting Room', 'Chain Hotel', '', '', '', '', ''),
(141, '', 'Opera PMS', 'Apptivo', '', 'Micros', 'Ideas', 'Choiceadvantage', 'Opera', '', 'OnQ', 'Azimut Hotel Pereslavl', 'azimuthotels.com/Russia/azimut-hotel-pereslavl/', 'Russia', 'Ulitsa Okruzhnaya, 29А', 'Rostov', '', '152151', '', 'Julia', 'Khrustaleva', 'General Manager', 'jkhrustaleva@azimuthotels.de', '7 495 272-01-40', 200, 5, 'US$ 94 - US$ 272', 'Restaurant & Meeting Room', 'Indepedent hotel', '', '', '', '', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `hotel`
--
ALTER TABLE `hotel`
  ADD PRIMARY KEY (`data_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `hotel`
--
ALTER TABLE `hotel`
  MODIFY `data_id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=142;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
